spring.application.name=welcome
spring.datasource.generateUniqueName=false
spring.datasource.name=welcomedb
spring.h2.console.enabled=true
spring.h2.console.settings.webAllowOthers=true
spring.jpa.showSql=true

